spring.application.name=PhoneVerdict

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/phone_verdict?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.produce-partial-output-while-processing=false

# Server
server.port=8080
server.error.whitelabel.enabled=false

# File upload
spring.servlet.multipart.max-file-size=10MB
